config/routes.rb
Workspace::Application.routes.draw do
  
  namespace :admin do
    
    root 'panel#principal'
    
    
    get  "panel/principal"
    get  "login" => 'panel#login'
    post "login" => 'panel#loguea'
    get  "logout" => 'panel#logout'
    
    resources :users
    resources :categories
    resources :products
    
  end
  
  
  root 'web#index'
  

end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :color
    belongs_to :material
    belongs_to :neck
    belongs_to :sleeve
    belongs_to :size
    has_many :orderdetails
    
    FOTOS = File.join Rails.root, 'public', 'photo_store'
    after_save :guardar_foto
    
    def photo=(file_data)
      unless file_data.blank?
      	@file_data = file_data
      	self.extension = file_data.original_filename.split('.').last.downcase
      end
    end
    
    def photo_filename
      File.join FOTOS, "#{id}.#{extension}"
    end
    
    def photo_path
      "/photo_store/#{id}.#{extension}"
    end
    
    def has_photo?
      File.exists? photo_filename
    end
    
    private
    
    def guardar_foto
      if @file_data
      	FileUtils.mkdir_p FOTOS
      	File.open(photo_filename, 'wb') do |f|
      		f.write(@file_data.read)
      	end
      	@file_data = nil
      end
    end
    
    
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  layout 'admin'
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [:admin,@product], notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [:admin,@product], notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :extension, :stock, :price, :color_id, :neck_id, :sleeve_id,  :size_id, :material_id, photo=(:photo))
    end
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin,@product], html: {multipart: true}) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Nombre" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Descripción" %><br>
    <%= f.text_field :description %>
  </div>
  
    <div class="field">
    <%= f.label "Color" %><br>
    <%= f.collection_select :color_id, Color.all, :id, :description, :prompt => true %>
  </div>
  
  <div class="field">
    <%= f.label "Tipo de cuello" %><br>
    <%= f.collection_select :neck_id, Neck.all, :id, :description, :prompt => true %>
  </div>
  
  <div class="field">
    <%= f.label "Tipo de manga" %><br>
    <%= f.collection_select :sleeve_id, Sleeve.all, :id, :description, :prompt => true %>
  </div>
  
  <div class="field">
    <%= f.label "Tamaño" %><br>
    <%= f.collection_select :size_id, Size.all, :id, :description, :prompt => true %>
  </div>
  
  <div class="field">
    <%= f.label "Material" %><br>
    <%= f.collection_select :material_id, Material.all, :id, :description, :prompt => true %>
  </div>
  
  <div class="field">
    <%= f.label "Foto" %><br>
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label "Stock" %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label "Precio" %><br>
    <%= f.text_field :price %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin,@product] %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Extension</th>
      <th>Stock</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.extension %></td>
        <td><%= product.stock %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', admin_product_path(product) %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @product.extension %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>